package saojudasexerc.a3projeto;




import com.sun.jdi.connect.spi.Connection;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author L Morais
 */
public class MenuADM extends javax.swing.JFrame {

    /**
     * Creates new form UsuariosAdministrador
     */
    public MenuADM() { // Construtor
        super("Central Usuarios");
        initComponents();
        setLocationRelativeTo(null);
        
        JOptionPane.showMessageDialog(null, "Cadastrar: campos usuario e senha!\nAtualizar: campos codigo, usuario e/ou senha!\nDeletar: campo codigo!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cadastrarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        atualizarButton = new javax.swing.JButton();
        exibirButton = new javax.swing.JButton();
        deletarButton = new javax.swing.JButton();
        codigoField = new javax.swing.JTextField();
        usuarioField = new javax.swing.JTextField();
        senhaField = new javax.swing.JTextField();
        explicacaoButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        cadastroTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 153));

        jPanel1.setBackground(new java.awt.Color(102, 0, 152));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.yellow, null, null));

        cadastrarButton.setBackground(new java.awt.Color(204, 204, 0));
        cadastrarButton.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        cadastrarButton.setText("Cadastrar");
        cadastrarButton.setToolTipText("");
        cadastrarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 0), null, new java.awt.Color(204, 204, 0)));
        cadastrarButton.setVerifyInputWhenFocusTarget(false);
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setBackground(new java.awt.Color(204, 204, 0));
        cancelarButton.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        cancelarButton.setText("Cancelar");
        cancelarButton.setToolTipText("");
        cancelarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 0), null, new java.awt.Color(204, 204, 0)));
        cancelarButton.setVerifyInputWhenFocusTarget(false);
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        atualizarButton.setBackground(new java.awt.Color(204, 204, 0));
        atualizarButton.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        atualizarButton.setText("Atualizar");
        atualizarButton.setToolTipText("");
        atualizarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 0), null, new java.awt.Color(204, 204, 0)));
        atualizarButton.setVerifyInputWhenFocusTarget(false);
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });

        exibirButton.setBackground(new java.awt.Color(204, 204, 0));
        exibirButton.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        exibirButton.setText("Atualizar Tabela");
        exibirButton.setToolTipText("");
        exibirButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 0), null, new java.awt.Color(204, 204, 0)));
        exibirButton.setVerifyInputWhenFocusTarget(false);
        exibirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirButtonActionPerformed(evt);
            }
        });

        deletarButton.setBackground(new java.awt.Color(204, 204, 0));
        deletarButton.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        deletarButton.setText("Deletar");
        deletarButton.setToolTipText("");
        deletarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 0), null, new java.awt.Color(204, 204, 0)));
        deletarButton.setVerifyInputWhenFocusTarget(false);
        deletarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarButtonActionPerformed(evt);
            }
        });

        codigoField.setBackground(new java.awt.Color(51, 51, 51));
        codigoField.setForeground(new java.awt.Color(255, 255, 255));
        codigoField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Codigo\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        codigoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoFieldActionPerformed(evt);
            }
        });

        usuarioField.setBackground(new java.awt.Color(51, 51, 51));
        usuarioField.setForeground(new java.awt.Color(255, 255, 255));
        usuarioField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        usuarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioFieldActionPerformed(evt);
            }
        });

        senhaField.setBackground(new java.awt.Color(51, 51, 51));
        senhaField.setForeground(new java.awt.Color(255, 255, 255));
        senhaField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Senha\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        senhaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFieldActionPerformed(evt);
            }
        });

        explicacaoButton.setBackground(new java.awt.Color(204, 204, 0));
        explicacaoButton.setFont(new java.awt.Font("Serif", 2, 18)); // NOI18N
        explicacaoButton.setText("Explicacao");
        explicacaoButton.setToolTipText("");
        explicacaoButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 0), null, new java.awt.Color(204, 204, 0)));
        explicacaoButton.setVerifyInputWhenFocusTarget(false);
        explicacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explicacaoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(usuarioField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addComponent(senhaField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atualizarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastrarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(explicacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exibirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(senhaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exibirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(explicacaoButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cadastroTable.setBackground(new java.awt.Color(102, 0, 152));
        cadastroTable.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        cadastroTable.setForeground(new java.awt.Color(255, 255, 255));
        cadastroTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Usuario", "Senha"
            }
        ));
        cadastroTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        cadastroTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        cadastroTable.setShowGrid(true);
        jScrollPane4.setViewportView(cadastroTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtonActionPerformed

        try {
            java.sql.Connection con =  Conexao.faz_conexao();    

            String sql = "INSERT INTO tb_Pessoas (usuario, senha) VALUES (?, ?)";
            
            Usuario user = new Usuario();
            user.setUsuario(usuarioField.getText());
            user.setSenha(senhaField.getText());
                   
            PreparedStatement stmt = con.prepareStatement(sql); 
            stmt.setString(1, user.getUsuario()); 
            stmt.setString(2, user.getSenha()); 
            
            stmt.executeUpdate(); 

            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");

            stmt.close();
            con.close(); 
            
        } catch (Exception e) { 
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Usuario já cadastrado!");
        }
    }//GEN-LAST:event_cadastrarButtonActionPerformed

    private void exibirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirButtonActionPerformed
        carregarTabela(); 
    }//GEN-LAST:event_exibirButtonActionPerformed

    private void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) cadastroTable.getModel(); 
        modelo.setNumRows(0);

        cadastroTable.getColumnModel().getColumn(0).setPreferredWidth(20); 
        cadastroTable.getColumnModel().getColumn(1).setPreferredWidth(60);
        cadastroTable.getColumnModel().getColumn(2).setPreferredWidth(60);

        try {
            java.sql.Connection con = Conexao.faz_conexao();  

            String sql = "SELECT * FROM tb_Pessoas"; 

            PreparedStatement stmt = con.prepareStatement(sql); 
            ResultSet rs = stmt.executeQuery(); 

            while (rs.next()) {
                modelo.addRow(new Object[]{ 
                        rs.getInt(1), 
                        rs.getString(2),
                        rs.getString(3) 
                });
            }

            stmt.close(); 
            con.close(); 

        } catch (Exception e) { 
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro!\nTente novamente!");
        }
}
    
    private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
        
        try {
            java.sql.Connection con =  Conexao.faz_conexao(); 

            String sql = "UPDATE tb_Pessoas SET usuario = ?, senha = ? WHERE codigo = ?"; 
            
            Usuario user = new Usuario();
            user.setUsuario(usuarioField.getText());
            user.setSenha(senhaField.getText());
            
            PreparedStatement stmt = con.prepareStatement(sql); 
            stmt.setString(1, user.getUsuario()); 
            stmt.setString(2, user.getSenha()); 
            stmt.setInt( 3, Integer.parseInt(codigoField.getText())); 
            stmt.executeUpdate(); 

            JOptionPane.showMessageDialog(null, "Atualizacao de dados realizado com sucesso!");

            stmt.close();
            con.close(); 
            
        }  catch (Exception e){ 
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro!\nTente novamente!");
        }
    
    }//GEN-LAST:event_atualizarButtonActionPerformed

    private void deletarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarButtonActionPerformed
        
        try {
            java.sql.Connection con =  Conexao.faz_conexao(); 
            
            String sql = "DELETE FROM tb_Pessoas WHERE codigo = ?"; 
            
            PreparedStatement stmt = con.prepareStatement(sql); 
            stmt.setInt(1, Integer.parseInt(codigoField.getText()));  
            stmt.executeUpdate(); 
            
            JOptionPane.showMessageDialog(null, "Os dados foram deletados com sucesso!");

            stmt.close();
            con.close();
        } catch (Exception e){ 
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro!\nTente novamente!");
        }
    }//GEN-LAST:event_deletarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        TelaLogin login = new TelaLogin();
        login.setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void codigoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoFieldActionPerformed

    private void usuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioFieldActionPerformed

    private void senhaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFieldActionPerformed

    private void explicacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explicacaoButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Cadastrar: campos usuario e senha!\nAtualizar: campos codigo, usuario e/ou senha!\nDeletar: campo codigo!");
    }//GEN-LAST:event_explicacaoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarButton;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTable cadastroTable;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JTextField codigoField;
    private javax.swing.JButton deletarButton;
    private javax.swing.JButton exibirButton;
    private javax.swing.JButton explicacaoButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField senhaField;
    private javax.swing.JTextField usuarioField;
    // End of variables declaration//GEN-END:variables
}
